#!/bin/bash
set -e 



psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    SELECT 'CREATE DATABASE ${USER_SERVICE_DB_NAME}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${USER_SERVICE_DB_NAME}')\gexec
    SELECT 'CREATE DATABASE ${PRODUCT_SERVICE_DB_NAME}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${PRODUCT_SERVICE_DB_NAME}')\gexec
    SELECT 'CREATE DATABASE ${USER_SERVICE_DB_TEST_NAME}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${USER_SERVICE_DB_TEST_NAME}')\gexec
    SELECT 'CREATE DATABASE ${PRODUCT_SERVICE_DB_TEST_NAME}' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${PRODUCT_SERVICE_DB_TEST_NAME}')\gexec

    GRANT ALL PRIVILEGES ON DATABASE ${USER_SERVICE_DB_NAME} TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${PRODUCT_SERVICE_DB_NAME} TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${USER_SERVICE_DB_TEST_NAME} TO ${POSTGRES_USER};
    GRANT ALL PRIVILEGES ON DATABASE ${PRODUCT_SERVICE_DB_TEST_NAME} TO ${POSTGRES_USER};
EOSQL

echo "Veritabanları (${USER_SERVICE_DB_NAME}, ${PRODUCT_SERVICE_DB_NAME}, ${USER_SERVICE_DB_TEST_NAME}, ${PRODUCT_SERVICE_DB_TEST_NAME}) oluşturuldu veya zaten vardı."