# user_service/Dockerfile.test
FROM python:3.12-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /code/requirements.txt

RUN pip install --no-cache-dir pytest httpx sqlalchemy-utils psycopg2-binary passlib[bcrypt]

COPY ./app /code/app

COPY ./tests /code/tests

CMD ["pytest", "/code/tests"]